apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels: # 3 fields under metadata , all at the same level
    environment: production
    trer: frontend
  namespace: demo-namespace2
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80