apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    environment: production
    trer: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80