apiVersion: v1
kind: Pod
metadata:
  name: mynginx4
spec:
  containers:
    - name: nginx-container4
      image: nginx
      ports:
        - containerPort: 80

#kubectl get pods -l 'environment' --show-labels -> environemt is defined
#kubectl get pods -l '!environment' --show-labels -> not defined